// <auto-generated />
using System;
using G2rismBeta.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace G2rismBeta.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251031133411_SecondCreateUsuarios")]
    partial class SecondCreateUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("G2rismBeta.API.Models.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_permiso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("accion");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("modulo");

                    b.Property<string>("NombrePermiso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_permiso");

                    b.HasKey("IdPermiso");

                    b.HasIndex("NombrePermiso")
                        .IsUnique()
                        .HasDatabaseName("idx_permiso_nombre_unique");

                    b.HasIndex("Modulo", "Accion")
                        .HasDatabaseName("idx_permiso_modulo_accion");

                    b.ToTable("permisos");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("NivelAcceso")
                        .HasColumnType("int")
                        .HasColumnName("nivel_acceso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol");

                    b.HasIndex("NivelAcceso")
                        .HasDatabaseName("idx_rol_nivel_acceso");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("idx_rol_nombre_unique");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.RolPermiso", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("int")
                        .HasColumnName("id_permiso");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_asignacion");

                    b.HasKey("IdRol", "IdPermiso")
                        .HasName("pk_roles_permisos");

                    b.HasIndex("IdPermiso");

                    b.ToTable("roles_permisos");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.TokenRecuperacion", b =>
                {
                    b.Property<int>("IdToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_token");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdToken"));

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_expiracion");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_generacion");

                    b.Property<DateTime?>("FechaUso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_uso");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("IpSolicitud")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("ip_solicitud");

                    b.Property<string>("TipoToken")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_token");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("token");

                    b.Property<bool>("Usado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("usado");

                    b.HasKey("IdToken");

                    b.HasIndex("FechaExpiracion")
                        .HasDatabaseName("idx_token_expiracion");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("idx_token_usuario");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_token_unique");

                    b.ToTable("tokens_recuperacion");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("bloqueado");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int?>("IdReferencia")
                        .HasColumnType("int")
                        .HasColumnName("id_referencia");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int")
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("tipo_usuario");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ultimo_acceso");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_usuario_email_unique");

                    b.HasIndex("Estado")
                        .HasDatabaseName("idx_usuario_estado");

                    b.HasIndex("TipoUsuario")
                        .HasDatabaseName("idx_usuario_tipo");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("idx_usuario_username_unique");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int?>("AsignadoPor")
                        .HasColumnType("int")
                        .HasColumnName("asignado_por");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_asignacion");

                    b.Property<DateTime?>("FechaExpiracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_expiracion");

                    b.HasKey("IdUsuario", "IdRol")
                        .HasName("pk_usuarios_roles");

                    b.HasIndex("IdRol")
                        .HasDatabaseName("idx_usuario_rol_rol");

                    b.HasIndex("IdUsuario")
                        .HasDatabaseName("idx_usuario_rol_usuario");

                    b.ToTable("usuarios_roles");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.RolPermiso", b =>
                {
                    b.HasOne("G2rismBeta.API.Models.Permiso", "Permiso")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rol_permiso_permiso");

                    b.HasOne("G2rismBeta.API.Models.Rol", "Rol")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rol_permiso_rol");

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.TokenRecuperacion", b =>
                {
                    b.HasOne("G2rismBeta.API.Models.Usuario", "Usuario")
                        .WithMany("TokensRecuperacion")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_token_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.UsuarioRol", b =>
                {
                    b.HasOne("G2rismBeta.API.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_rol");

                    b.HasOne("G2rismBeta.API.Models.Usuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_rol_usuario");

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Permiso", b =>
                {
                    b.Navigation("RolesPermisos");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Rol", b =>
                {
                    b.Navigation("RolesPermisos");
                });

            modelBuilder.Entity("G2rismBeta.API.Models.Usuario", b =>
                {
                    b.Navigation("TokensRecuperacion");

                    b.Navigation("UsuariosRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
